id = "clarity"
name = "Clarity"
version = "0.0.1"
schema_version = 1
authors = ["Hugo <hugo@hiro.so>"]
description = "Clarity language support"
repository = "https://github.com/hirosystems/clarity-zed"

[language_servers.clarity-lsp]
name = "Clarity Language Server"
language = "Clarity"

[grammars.clarity]
repository = "https://github.com/xlittlerag/tree-sitter-clarity"
commit = "7fa54825fdd971a1a676f885384f024fe2b7384a"
